import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { FileCode, Star, ChevronDown, ChevronRight } from "lucide-react";
import RunStageCTA from "../RunStageCTA";
import { Badge } from "@/components/ui/badge";
import StageIntro from "../StageIntro";
import { STAGE_INTROS } from "../stageIntroData";
import { supabase } from "@/integrations/supabase/client";
import ArtifactContent from "./ArtifactContent";
import EnterpriseRequirementDashboard from "./requirement-analysis/EnterpriseRequirementDashboard";
import CriticPanel from "../critic/CriticPanel";
import { recoverArtifactContent } from "@/lib/artifact-utils";

function ArtifactCard({ artifact, index }: { artifact: any; index: number }) {
  const [expanded, setExpanded] = useState(index === 0);

  const statusColors: Record<string, string> = {
    generated: "bg-primary/10 text-primary border-primary/30",
    locked: "bg-success/10 text-success border-success/30",
    approved: "bg-success/10 text-success border-success/30",
    draft: "bg-muted text-muted-foreground border-border",
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: index * 0.04 }}
      className="rounded-xl border bg-card overflow-hidden hover:shadow-sm transition-shadow"
    >
      <button
        onClick={() => setExpanded(!expanded)}
        className="flex items-center gap-3 p-4 w-full text-left hover:bg-accent/30 transition-colors"
      >
        {expanded ? (
          <ChevronDown className="h-4 w-4 text-muted-foreground" />
        ) : (
          <ChevronRight className="h-4 w-4 text-muted-foreground" />
        )}
        <Badge variant="outline" className="text-[10px] font-mono">
          {artifact.type.replace(/_/g, " ")}
        </Badge>
        <h4 className="font-display font-semibold text-sm flex-1">{artifact.title}</h4>
        <Badge
          className={`text-[9px] border ${statusColors[artifact.status] || statusColors.draft}`}
        >
          {artifact.status}
        </Badge>
      </button>
      {expanded && (
        <div className="px-4 pb-4 border-t">
          {artifact.generated_by && (
            <div className="flex items-center gap-2 py-2.5 text-[11px] text-muted-foreground border-b border-border/40 mb-3">
              <Star className="h-3 w-3 text-primary/60" />
              <span>
                Generated by{" "}
                <span className="font-semibold text-foreground">{artifact.generated_by}</span>
              </span>
              <span className="ml-auto tabular-nums">
                {new Date(artifact.created_at).toLocaleString()}
              </span>
            </div>
          )}
          <ArtifactContent content={artifact.content} />
        </div>
      )}
    </motion.div>
  );
}

export default function RequirementAnalysisWorkspace({
  projectId,
  refreshKey,
  onRunStage,
  stageRunning,
}: {
  projectId: string;
  refreshKey?: number;
  onRunStage?: () => void;
  stageRunning?: boolean;
}) {
  const [artifacts, setArtifacts] = useState<any[]>([]);
  const [requirements, setRequirements] = useState<any[]>([]);

  useEffect(() => {
    const fetchData = async () => {
      const [artRes, reqRes] = await Promise.all([
        supabase
          .from("architecture_artifacts")
          .select("*")
          .eq("project_id", projectId)
          .eq("stage", 2)
          .order("created_at", { ascending: false }),
        supabase
          .from("requirements")
          .select("id, requirement_id, title, type, status, priority")
          .eq("project_id", projectId)
          .order("requirement_id"),
      ]);
      if (artRes.data) setArtifacts(artRes.data);
      if (reqRes.data) setRequirements(reqRes.data);
    };
    fetchData();
  }, [projectId, refreshKey]);

  const draftReqs = requirements.filter((r) => r.status === "draft");
  const approvedReqs = requirements.filter((r) => r.status === "approved" || r.status === "locked");

  return (
    <div className="space-y-6">
      <StageIntro {...STAGE_INTROS[2]} title="Requirement Analysis" />

      <div className="grid grid-cols-3 gap-3">
        <motion.div
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          className="rounded-xl border bg-card p-4 text-center"
        >
          <p className="text-2xl font-bold tabular-nums text-foreground">{requirements.length}</p>
          <p className="text-[10px] text-muted-foreground font-medium mt-0.5">Total Requirements</p>
        </motion.div>
        <motion.div
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.05 }}
          className="rounded-xl border bg-success/5 border-success/20 p-4 text-center"
        >
          <p className="text-2xl font-bold tabular-nums text-success">{approvedReqs.length}</p>
          <p className="text-[10px] text-muted-foreground font-medium mt-0.5">Finalized</p>
        </motion.div>
        <motion.div
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="rounded-xl border bg-warning/5 border-warning/20 p-4 text-center"
        >
          <p className="text-2xl font-bold tabular-nums text-warning">{draftReqs.length}</p>
          <p className="text-[10px] text-muted-foreground font-medium mt-0.5">Pending Review</p>
        </motion.div>
      </div>

      {artifacts.length === 0 ? (
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center py-16 rounded-xl border border-dashed border-border/60 bg-card/30"
        >
          <div className="h-16 w-16 rounded-2xl bg-primary/10 flex items-center justify-center mx-auto mb-4">
            <FileCode className="h-8 w-8 text-primary/40" />
          </div>
          <p className="text-muted-foreground text-sm font-medium mb-1.5">
            No analysis generated yet
          </p>
          <RunStageCTA
            stageLabel="Requirement Analysis"
            onRun={onRunStage}
            running={stageRunning}
          />
        </motion.div>
      ) : (
        <div className="space-y-6">
          {(() => {
            // Pick the primary (non-challenger) artifact for the structured dashboard
            const primary = artifacts.find(
              (a) =>
                !a.generated_by?.includes("Challenger") && !a.generated_by?.includes("Evaluator"),
            );
            const structured = primary ? recoverArtifactContent(primary.content) : null;
            const hasStructured =
              structured &&
              (structured.functional_requirements?.length ||
                structured.non_functional_requirements?.length ||
                structured.ambiguities?.length);
            return (
              <>
                {hasStructured && (
                  <motion.div
                    initial={{ opacity: 0, y: 8 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.3 }}
                  >
                    <EnterpriseRequirementDashboard content={structured} />
                  </motion.div>
                )}
                {requirements.length > 0 && (
                  <CriticPanel projectId={projectId} stage={2} itemTypeLabel="requirements" />
                )}
                <div className="space-y-3">
                  <h3 className="text-[11px] uppercase tracking-wider font-semibold text-muted-foreground px-1">
                    Raw Analysis Artifacts
                  </h3>
                  {artifacts.map((artifact, i) => (
                    <ArtifactCard key={artifact.id} artifact={artifact} index={i} />
                  ))}
                </div>
              </>
            );
          })()}
        </div>
      )}
    </div>
  );
}
